### ISSUE TITLE
leaflet 1.6.0 : tiles not loaded when scroll reveal them

### ISSUE THREAD

**Issue by brunob** [jieter/leaflet.layerscontrol-minimap#14]
Hi @jieter i've tried to update https://github.com/leaflet-extras/leaflet-providers/blob/master/preview/index.html to leaflet 1.6.0 with a latest version of  leaflet.layerscontrol-minimap and it works almost well. There's only one problem, when i scroll the pane to show originally hidden layers, their tiles are not shown.

**Comment by brunob** [comment]
After a bit of logging, it seems that we never pass in `_onListScroll'')` when the pane is scrolled, called from here https://github.com/jieter/leaflet.layerscontrol-minimap/blob/master/L.Control.Layers.Minimap.js#L63

If i change the event to wheel or click, it works, so it may be a bug in leaflet core, and maybe this one https://github.com/Leaflet/Leaflet/issues/7077

**Comment by n-a-m-e** [comment]
Hi @brunob,
You need to update the control.layers.minimap.css and L.Control.Layers.Minimap.js to the ones in this repository and then add the following to the control.layers.minimap.css
`
.leaflet-control-layers-minimap .leaflet-control-layers-scrollbar{
	overflow-y: unset;
	overflow-x: unset;
}
`
seems to fix the issue and is working for leaflet 1.7.1.
I also created a pull request with @jieter to include this in the css file

**Comment by brunob** [comment]
Nice catch @n-a-m-e and thx for the PR.

**Comment by jieter** [comment]
released 1.0.21
