### ISSUE TITLE
This plugin seems to break automated map animation.

### ISSUE THREAD

**Issue by jb2b38** [jieter/Leaflet.layerscontrol-minimap#2]
I've been using this call to center a POI on the map:
map.setView(marker.getLatLng(), map.getZoom(), {animate: true} );

I later added your plugin, but it breaks on that line. Removing it solves the problem, but I'm losing an expected behaviour. Maybe linked with the sync plugin that is not transmitted for animations?

**Comment by jieter** [comment]
@jb2b38 thanks for reporting. Might be a sync issue indeed. Can you setup a minimal example in a jsfiddle to show the problem?

**Comment by jb2b38** [comment]
Sure, here it is:
https://jsfiddle.net/2jky6z3u/3/
Click on the button to trigger the automated animation, it won't work. If you change the code to not use the plugin but use default layer control, it will work.

**Comment by jieter** [comment]
Seems like the fiddle doesn't work...

**Comment by jb2b38** [comment]
Mmm, I'm new using jsfiddle to share what I write to others... Maybe this link works better? https://jsfiddle.net/2jky6z3u/3/#&togetherjs=RQFwnwKqPg

**Comment by jb2b38** [comment]
The problem seems to be slightly more complicated. I didn't manage to reproduce it in JSFiddle for now, but here's the global situation: an action triggers a map resize and a center on a point.
When changing the animate: true to false, I get it to work, even though it's less elegant.
The animation clashes with the mini-map during the resize.

map.setView(marker.getLatLng(), map.getZoom(), {animate: false} );
$("#map-div").animate({width: "50%"}, 300, "swing", function() {
	map.invalidateSize(true);
});

**Comment by jieter** [comment]
hmm, clearly something wrong as having the code loaded in the browser prevents the map from loading correctly...

**Comment by jieter** [comment]
Hmm, not clear what the issue is here, please update leaflet and leaflet.layerscontrol-minimap and reopen with a minimal test case exposing the problem.
