### ISSUE TITLE
Using on multiple maps Leaflet maps on the same page.

### ISSUE THREAD

**Issue by jdgodchaux** [jieter/Leaflet.layerscontrol-minimap#4]
Hello!

Thank you for an excellent library! I'm running into a problem where when I try to create minimap controls on multiple, unrelated Leaflet maps on the same webpage, the minimaps are showing no basemaps or overlays on every map after the first one. Here's an example of what I'm seeing (the maps are interspersed in the content and you may need to scroll down a bit to see the maps subsequent to the first):

http://hoodmapping.org/urban-design-chicago/team-5/

I suspect it might be a related issue to [this one](http://gis.stackexchange.com/questions/66193/multiple-instance-of-leaflet-on-my-page) describing problems with showing multiple Leaflet maps on one page. In our example, we're creating maps in `app.map[mapId]` where `mapId` is a unique string of the form `map_#`. We're calling the minimap library like this:

```
L.control.layers.minimap(app.baseMaps[mapId], app.overlayMaps[mapId], {
      overlayBackgroundLayer: app.map[mapId].tiles,
      collapsed: collapsed,
}).addTo(app.map[mapId]);
```

You can see the operative javascript [here](https://github.com/NiJeLorg/Chicago-Neighborhoods/blob/master/uchicago/neighborhoods/static/neighborhoods/js/app.js#L101). Our [`app.createMap`](https://github.com/NiJeLorg/Chicago-Neighborhoods/blob/master/uchicago/neighborhoods/static/neighborhoods/js/app.js#L41) function runs every time we want a new map created, and thus a new set of minimap layer controls. 

Any help you could provide would be much appreciated! Thank you!

**Comment by jieter** [comment]
Interesting, the layer is cloned so I would not expect problems reusing it, I'll try to look into it next week.

**Comment by jieter** [comment]
The problem was in using an overly broad query for the minimaps DOM nodes, should be fixed now, released leaflet.layerscontrol-minimap@1.0.10.

**Comment by jdgodchaux** [comment]
Awesome! Thank you!!
