### ISSUE TITLE
Minimaps do not appear when collapsed:true

### ISSUE THREAD

**Issue by ussisoo** [jieter/Leaflet.layerscontrol-minimap#5]
When collapsed is set to true, then the minimaps do not appear
https://jsfiddle.net/vmg3zf1y/1/ 
 (you have to press on the external resorces links to enable https connections)

I think it has something do to with the _onListScroll function and that it can not get the correct value for: var scrollTop = container.scrollTop;

If you set collapsed:false everything works.

**Comment by jieter** [comment]
Indeed, both values for `first` and `last` are `-1` in `_onListScroll()`, bacause `this.isCollapsed()` returned `true`.

Leaflet renamed the methods a bit, I did not follow yet with leaflet-layerscontrol-minimap. Fixed in v1.0.16

**Comment by ussisoo** [comment]
scrollTop = container.scrollTop; seems to be getting the wrong value when there are many minimaps on list and you have to scroll the list. See the fiddle provided above and scroll to the bottom. The minimaps do not appear in the bottom.

**Comment by jieter** [comment]
@ussisoo the fiddle doesn't work for me, some resources blocked by client.

**Comment by ussisoo** [comment]
try this: https://jsfiddle.net/vmg3zf1y/4/

**Comment by jieter** [comment]
Thanks, confirmed.
