### ISSUE TITLE
Error: map not defined

### ISSUE THREAD

**Issue by giorgim** [jieter/Leaflet.layerscontrol-minimap#6]
`        if (!map) { return; }
`
I get an **error** that map is not defined on above line (Line 72, L.Control.Layers.Minimap.js). Why?
https://github.com/jieter/Leaflet.layerscontrol-minimap/blob/gh-pages/L.Control.Layers.Minimap.js#L72

When I commented that line, if I start the map in collapsed state it seems to work OK, if I start in **not** collapsed state, when I hover the control, the individual map entries are shown but no minimaps along them.

I installed via npm

**Comment by jieter** [comment]
Thanks for reporting, stupid typo carelessly released.

Fixed by a962b9a and released v1.0.18. Please verify if that fixes your problem.

**Comment by giorgim** [comment]
ok, please make sure sure npm package is also updated.

**Comment by jieter** [comment]
published 11 hours ago
1.0.18 is the latest of 13 releases
