### ISSUE TITLE
nothing happens when layer choice from leaflet 1.1.0

### ISSUE THREAD

**Issue by t2-yoshida** [jieter/Leaflet.layerscontrol-minimap#8]
this plugin is nice.
but, It seems Leaflet.layerscontrol-minimap 1.0.18  not work leaflet 1.1.0 and later.

**quick fix**
- L.Control.Layers.Minimap.js
`099. }`
`+ this._layerControlInputs.push(input);`
`100. input.layerId = L.stamp(obj.layer);`
`101. span.appendChild(input);`

**Comment by jieter** [comment]
@t2-yoshida fixed with 75701d8, released 1.0.19.

Next time, if you can, please open a PR.
